- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps With AWS" # play level variable
    DURATION: "120 Hours"
    TRAINER: "Siva"

  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "Iam learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"

  - name: print the info 2
    vars:
      COURSE: "Ansible"  # task level variable
    ansible.builtin.debug:
      msg: "Iam learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
