- name: variables to print
  hosts: web
  vars:
    COURSE: DevOps With AWS
    DURATION: "120 Hours"
    Trainer: "Siva"

  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "Iam learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
      