- name: Create EC2 Instaces & R53 records
  hosts: local
  connection: local
  vars_files: 
  - ../vars.yaml

  tasks:
  - name: create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

