- name: Create EC2 Instaces & R53 records
  hosts: local
  connection: local
  vars_files: 
  - ../vars.yaml

  tasks:
  - name: ansible to install boto3 and botocore
    # install boto3 botocore` to enable your Ansible server to interact with AWS services programmatically. 
    ansible.builtin.pip:
      name:
      - boto3
      - botocore

  - name: create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output   # task to print output of instances. copy o/p of this task andpaste in Notepad, view as language JSON.
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

        #private IP R53
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.devopslearn.store
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #devopslearn.store
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend" #when keyword should not have {{}}